/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UstawieniaRouteImport } from './routes/ustawienia'
import { Route as PlatnoscRouteImport } from './routes/platnosc'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as IndexRouteImport } from './routes/index'

const UstawieniaRoute = UstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatnoscRoute = PlatnoscRouteImport.update({
  id: '/platnosc',
  path: '/platnosc',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historia': typeof HistoriaRoute
  '/platnosc': typeof PlatnoscRoute
  '/ustawienia': typeof UstawieniaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historia': typeof HistoriaRoute
  '/platnosc': typeof PlatnoscRoute
  '/ustawienia': typeof UstawieniaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historia': typeof HistoriaRoute
  '/platnosc': typeof PlatnoscRoute
  '/ustawienia': typeof UstawieniaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/historia' | '/platnosc' | '/ustawienia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/historia' | '/platnosc' | '/ustawienia'
  id: '__root__' | '/' | '/historia' | '/platnosc' | '/ustawienia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoriaRoute: typeof HistoriaRoute
  PlatnoscRoute: typeof PlatnoscRoute
  UstawieniaRoute: typeof UstawieniaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ustawienia': {
      id: '/ustawienia'
      path: '/ustawienia'
      fullPath: '/ustawienia'
      preLoaderRoute: typeof UstawieniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platnosc': {
      id: '/platnosc'
      path: '/platnosc'
      fullPath: '/platnosc'
      preLoaderRoute: typeof PlatnoscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoriaRoute: HistoriaRoute,
  PlatnoscRoute: PlatnoscRoute,
  UstawieniaRoute: UstawieniaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
